cloud.aws.credentials.accessKey:
cloud.aws.credentials.secretKey: 
cloud.aws.credentials.instanceProfile: false
cloud.aws.region.static: eu-west-1

sqs.queue: test-queue
sqs.queue.sns.fanout: test-queue-sns
sns.topic: test-topic

localstack:
  sns:
    url: http://localhost:4575
  sqs:
    url: http://localhost:4576

---

spring.profiles: prod
cloud.aws.credentials.instanceProfile: true